databases:
  - name: futyoukaizenn_db
    databaseName: futyoukaizenn_db
    user: futyoukaizenn
    region: singapore

services:
  - type: web
    name: futyoukaizenn
    env: ruby
    region: singapore
    plan: free
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: futyoukaizenn_db
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false